version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    dockerfile: Dockerfile
    ports:
      - "80:80"  # Map host port 80 to container port 80
    restart: on-failure


